### ISSUE TITLE
Porkbun API rate limit of 1 query/second (presumably by API key)

### ISSUE THREAD

**Issue by DazWilkin** [nrdcg/porkbun#3]
I'm using your SDK (thank you for it!) for a [Prometheus Exporter for Porkbun](https://github.com/DazWilkin/porkbun-exporter).

The exporter can be configured to query multiple domains.

I noticed that I was receiving 503s from Porkbun when making multiple requests.

Porkbun support told me that there's a 1 query/second rate limit on the API.

The support engineer is going to propose reflecting this in Porkbun's API documentation.

I think it would be useful to reflect in this SDK's README too.

**Comment by ldez** [comment]
> 1 query/second rate limit on the API.

It's extremely slow for an API.

**Comment by ldez** [comment]
:thinking: it's weird because I use the client inside [lego](https://github.com/go-acme/lego) and there are more than 1 req/s.

**Comment by DazWilkin** [comment]
Interesting.

A Porkbun support engineer told me that there's a limit.

I'm a new (this week) domain only credit card customer of Porkbun.

Perhaps it applies only to (folks like) me!?

I was able to repro the 503s using curl and, after applying a rate limiter to my code (using this SDK), the errors have stopped.

**Comment by DazWilkin** [comment]
It *could* be that the limit only applies to the `/ssl` endpoint?

I assume you weren't using that in lego (since it wasn't in the SDK)

And, thinking about your comment, I'd **not** experienced this limit using the `/dns` endpoints.

**Comment by ldez** [comment]
I also think that is a rate limit by endpoint: 1 req/s for to add records it's very very slow.
So yes maybe it's only on the `/ssl` endpoint.

**Comment by ldez** [comment]
I will close the issue, but add a message here if you have more information.

**Comment by jpluscplusm** [comment]
> So yes maybe it's only on the `/ssl` endpoint.

No, a too-low rate limit /definitely/ applies to (at least) Porkbun's `/v3/dns/create/<ZONE>` record-creation (/not/ zone creation!) API endpoint.

I'm not using this repo's tool, but this issue was the top hit when I searched, so I thought I'd drop this info in here :-)

**Comment by ldez** [comment]
I still think that all endpoints don't have the same rate limits.
Porkun needs to clarify that.
