### ISSUE TITLE
README title typo "Go library for accessing the Porkdun API"

### ISSUE THREAD

**Issue by DazWilkin** [nrdcg/porkbun#4]
r/Pork<b>d</b>un/Pork<b>b</b>un

**Comment by ldez** [comment]
feel free to open a PR :smile:

**Comment by ldez** [comment]
fixed in b6c205cfff5905b413f524b78dd7007ad584bc2d

**Comment by DazWilkin** [comment]
Thanks... I respect your process but forking, commit, PR for a single character markdown change is onerous.

**Comment by ldez** [comment]
You can do that inside the GitHub interface in 2 clicks :wink:
