### ISSUE TITLE
If Porkbun API endpoint results in 503, HTML is returned in the response body

### ISSUE THREAD

**Issue by DazWilkin** [nrdcg/porkbun#5]
After adding support for Porkbun's `/ssl` endpoint, I'm able to generate 503s by exceeding 1qps.

The [`http#Client.Do`](https://pkg.go.dev/net/http#Client.Do) does not return an error but this SDK returns an error on not `http.StatusOK`.

Because the Porkbun API returns HTML, the HTML is returned as the `ServerError.Message` which results in messy log message, e.g.:

```
status: 503 message: <html>
head><title>503 Service Temporarily Unavailable</title></head>
<body>
<center><h1>503 Service Temporarily Unavailable</h1></center>
<hr><center>openresty</center>
</body>
</html>
```

(Unfortunately) Porkbun support told me that they're unable to trap 503s (!?) as this is thrown by NGINX not their API server

I'm currently trapping this issue in my Exporter that uses this SDK but it may be better to trap it in the SDK.

**Propose**: capturing 503 (only) and replacing a standard "service unavailable" message.

**Comment by ldez** [comment]
It's a problem with their API, they have to fix that.
I don't know openresty but I'm sure that can be handled.

After the story about the rate limit, I think we have to don't trust their support.

**Comment by ldez** [comment]
after some research, it seems to be the default (maybe more than the default?) behavior of openresty.
What a lousy tool!
